services:
  app:
    build:
      context: .
      target: base
    ports:
      - "5175:5175"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - HOST=0.0.0.0
      - PORT=5175
    command: npm run dev -- --host 0.0.0.0 --port 5175
